"""Type stub for the nanobind module cemkit._kernel (bindings/python/module.cpp, ADR-012).

Each call takes one JSON request (docs/capi.md) and returns (status, JSON response); status is a
cemkit_status from kernel/cemkit/capi/cemkit.h. Use cemkit.kernel, not this module, directly.
"""

def abi_version() -> tuple[int, int, int]: ...
def kernel_version() -> str: ...
def spec_compile(request: str) -> tuple[int, str]: ...
def feasibility(request: str) -> tuple[int, str]: ...
def l0_batch(request: str) -> tuple[int, str]: ...
def geometry_smoke(request: str) -> tuple[int, str]: ...
