#!/usr/bin/env bash
# Regenerates docs/toolchain.md from the built image (run on the host, after scripts/docker-build.sh).
# The "Snapshot refresh log" section is hand-maintained and preserved across regenerations.
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$root/docs/toolchain.md"
image="${1:-fancem-dev:latest}"
# shellcheck disable=SC1091
. "$root/docker/pins.env"

image_id="$(docker image inspect "$image" --format '{{.Id}}')"
image_size="$(docker image inspect "$image" --format '{{.Size}}' | awk '{printf "%.2f GB", $1/1e9}')"
created="$(docker image inspect "$image" --format '{{.Created}}')"
versions="$("$root/scripts/dev.sh" scripts/versions.sh 2>&1 | sed -E 's/ +(OK|MISMATCH) +expected=([^ ]+) +actual=(.*)$/ | \1 | \2 | \3/; s/^([^ |]+) +\|/\1 |/' )"

refresh_log="$(sed -n '/^## Snapshot refresh log/,$p' "$out" 2>/dev/null || true)"
[ -n "$refresh_log" ] || refresh_log="## Snapshot refresh log

Each deliberate refresh of \`UBUNTU_SNAPSHOT\` (or of any other pin) is logged here: date, old value, new value, reason.

| Date | Pin | Old | New | Reason |
|---|---|---|---|---|
| ${created%%T*} | UBUNTU_SNAPSHOT | — | ${UBUNTU_SNAPSHOT} | Initial pin (T01) |"

cat > "$out" <<DOC
# Toolchain

Generated by \`scripts/gen-toolchain-doc.sh\` from \`docker/pins.env\` and the built image. Do not edit above the
refresh log. Decision record: \`docs/adr/006-toolchain-pins-openfoam-version.md\`.

## Image

| Item | Value |
|---|---|
| Local image | \`${image}\` |
| Image ID (config digest) | \`${image_id}\` |
| Size | ${image_size} |
| Built | ${created} |
| Base image | \`${UBUNTU_BASE}\` |
| Ubuntu snapshot | \`${UBUNTU_SNAPSHOT}\` |

The image ID identifies this local build. A registry digest exists only after the image is pushed; record it
here when that happens. Rebuilding from the same pins gives the same package versions, but the image ID can
differ because layer timestamps differ.

## Versions in the image (checked by \`scripts/versions.sh\`)

| Tool | Status | Pinned | Actual |
|---|---|---|---|
$(echo "$versions" | grep -E '\| (OK|MISMATCH) \|' | sed -E 's/^([^|]+)\|/| \1|/; s/$/ |/')

## Pin rule

Nothing published in the 14 days before the pin date. Pin date 2026-10-09; cutoff 2026-09-25.

${refresh_log}
DOC
echo "wrote $out"
