"""Renders the REL-002 error-code files from the kernel's error-code table.

The single source is k_error_codes in kernel/cemkit/core/error.hpp. The kernel tool
cemkit_core_print_error_codes prints it as JSON; this script renders from that JSON:
  docs/models/platform/error-codes.md   (human-readable list, with the TRUST-004 mapping)
  schemas/cemkit/v1/error-codes.json    (JSON Schema for Python and stored data; names are stored)
Never edit those files by hand: change error.hpp, rebuild, and run this script.

Usage:
  gen_error_codes.py --tool build/gcc-debug/kernel/cemkit/core/cemkit_core_print_error_codes
  gen_error_codes.py --tool <same> --check   # drift test: exit 1 if the committed files differ

Standard library only: the drift test runs as a ctest with the container's system Python.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

MARKDOWN = Path("docs/models/platform/error-codes.md")
SCHEMA = Path("schemas/cemkit/v1/error-codes.json")
SOURCE = "kernel/cemkit/core/error.hpp"
NAME = re.compile(r"^[a-z][a-z0-9_]*$")

# TRUST-004 simulation statuses that end a candidate, and the failure code each is classified as.
# VERIFIED and CONVERGED are not failures. The status type itself arrives with M3.
TRUST_004_MAPPING = (
    ("SOLVER_FAILED", "sim_untrusted"),
    ("UNCONVERGED", "sim_untrusted"),
    ("MESH_INVALID", "mesh_failed"),
    ("RESOURCE_LIMIT", "resource_exceeded"),
)


class TableError(ValueError):
    """The error-code table printed by the kernel tool is malformed."""


@dataclass(frozen=True)
class Code:
    code: int
    name: str
    meaning: str


def validate(raw: list[dict[str, Any]]) -> list[Code]:
    """Codes 1..N in order, unique snake_case names, non-empty meanings."""
    if not raw:
        raise TableError("no error codes in the table")
    codes: list[Code] = []
    for index, entry in enumerate(raw, start=1):
        if set(entry) != {"code", "name", "meaning"}:
            raise TableError(f"entry {index} must have exactly the fields code, name, meaning")
        code = Code(int(entry["code"]), str(entry["name"]), str(entry["meaning"]))
        if code.code != index:
            raise TableError(f"codes must be numbered 1..{len(raw)} in order; got {code.code}")
        if not NAME.match(code.name):
            raise TableError(f"name {code.name!r} is not snake_case")
        if not code.meaning:
            raise TableError(f"{code.name} has no meaning")
        if any(c.name == code.name for c in codes):
            raise TableError(f"name {code.name} appears twice")
        codes.append(code)
    return codes


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def _escape(text: str) -> str:
    return _cell(text).replace("_", "\\_")


def render_markdown(codes: list[Code]) -> str:
    names = {c.name for c in codes}
    for status, name in TRUST_004_MAPPING:
        if name not in names:
            raise TableError(f"TRUST-004 status {status} maps to {name}, which is not a code")
    lines = [
        "# Error codes (REL-002)",
        "",
        f"<!-- Generated by scripts/gen_error_codes.py from {SOURCE}. Do not edit. -->",
        "",
        "Every failure is classified with exactly one of these codes. The list is append-only: a",
        "code is never renamed, renumbered or reused, and new codes are added at the end. Stored",
        "data and the JSON interface use the name; the integer is used only across the C ABI.",
        "0 is never a valid code. JSON Schema: `schemas/cemkit/v1/error-codes.json`.",
        "",
        "| Code | Name | Meaning |",
        "| ---: | --- | --- |",
        *(f"| {c.code} | `{c.name}` | {_cell(c.meaning)} |" for c in codes),
        "",
        "## Simulation statuses (TRUST-004)",
        "",
        "Simulation results carry their own status (a separate type, added in M3). A status that",
        "ends a candidate is classified as follows; VERIFIED and CONVERGED are not failures.",
        "",
        "| TRUST-004 status | Error code |",
        "| --- | --- |",
        *(f"| {_escape(status)} | `{name}` |" for status, name in TRUST_004_MAPPING),
        "",
        "## What an error carries",
        "",
        "- the code;",
        "- a message;",
        "- a subject: the spec field path or model parameter concerned (may be empty);",
        "- details: key/value pairs sorted by key, conventionally `value`, `unit`, `bounds` and",
        "  `model`.",
        "",
        "`not_implemented` (owner decision D4) is used only for a capability the spec declares",
        "(a requested family, or a hook of that family) that this release does not provide. Its",
        "details always include `capability`, naming the missing capability (for example",
        "`fans.axial_ducted.initial_design`). It is never a placeholder inside half-written code.",
        "",
        "Messages are deterministic: no memory addresses and no locale-dependent formatting.",
        "Numbers are written in the shortest form that reads back to the same value.",
        "",
    ]
    return "\n".join(lines)


def render_schema(codes: list[Code]) -> str:
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:cemkit:schema:v1:error-codes",
        "title": "cemkit error code",
        "description": (
            f"REL-002 failure code, stored by name. Generated by scripts/gen_error_codes.py from "
            f"{SOURCE}; do not edit. x-cemkit-code is the fixed integer used across the C ABI."
        ),
        "type": "string",
        "oneOf": [
            {"const": c.name, "x-cemkit-code": c.code, "description": c.meaning} for c in codes
        ],
    }
    return json.dumps(schema, indent=2, ensure_ascii=False) + "\n"


def load(tool: Path) -> list[Code]:
    output = subprocess.run([str(tool)], capture_output=True, text=True, check=True).stdout
    raw = json.loads(output)
    if not isinstance(raw, list):
        raise TableError("the tool must print a JSON array")
    return validate(raw)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tool", type=Path, required=True, help="cemkit_core_print_error_codes")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true", help="compare instead of writing")
    args = parser.parse_args(argv)

    codes = load(args.tool)
    rendered = {MARKDOWN: render_markdown(codes), SCHEMA: render_schema(codes)}
    stale = []
    for relative, text in rendered.items():
        path = args.root / relative
        if args.check:
            current = path.read_text(encoding="utf-8") if path.is_file() else None
            if current != text:
                stale.append(relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    for relative in stale:
        print(f"gen_error_codes: {relative} is out of date with {SOURCE}; regenerate it")
    if args.check and not stale:
        print(f"gen_error_codes: {len(codes)} codes, generated files are current")
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
